src/bundle/mod.rs
src/main.rs

This fixes a couple typos in `main.rs`, including one that caused the "copyright" field in Bundle.toml to set `settings.version_str` rather than `settings.copyright`.

Set settings.copyright correctly.

---

.gitignore
Cargo.lock
Cargo.toml
Readme.md
src/bundle/osx_bundle.rs
src/main.rs

This change does a couple things:
* Allows the `icon` field in `Bundle.toml` to be an array of strings (or a single string, as before), so you can provide multiple sizes/formats of icon.  That means that `Settings` now stores a `Vec` of icon paths rather than a single icon path.
* Adds icon conversion support for OSX bundles.  If an ICNS file is provided, it uses that; otherwise it reads in the provided images(s) and packs them into an ICNS file.  High-DPI icons are supported.
Caveats:
* Using the `image` crate (which provides conversions from various image formats) does add a bunch of extra transitive dependencies for all the image formats it supports.  If this is a concern, we could set the `features` for that create to only pull dependencies for the formats we need most (mostly PNG and …

Automatically convert icon(s) to ICNS file for OSX bundle

---

Cargo.lock
Cargo.toml
src/bundle/deb_bundle.rs
src/main.rs

With these changes, I am now able to run `cargo bundle` on a Debian machine and successfully install the resulting package with `dpkg -i`.

Fix remaining issues preventing deb bundles from working

---

Cargo.lock
Cargo.toml
src/bundle/common.rs
src/bundle/deb_bundle.rs
src/bundle/mod.rs
src/bundle/osx_bundle.rs

Cargo-bundle will now include the app icons specified in Bundle.toml to be installed by the generated .deb package, automatically converting to PNG from other formats as necessary.

Generate icon files for deb bundles

---

Readme.md
src/bundle/deb_bundle.rs
src/main.rs

These fields are needed for both deb bundles and rpm bundles, each of which requires both a one-line description and a longer, multi-line description.

Add config fields for short and long descriptions

---

src/bundle/common.rs
src/bundle/deb_bundle.rs
src/bundle/ios_bundle.rs
src/bundle/mod.rs
src/bundle/osx_bundle.rs
src/main.rs

Implements initial support for iOS app bundles, which are a slight variation on OS X app bundles (see https://developer.apple.com/go/?id=bundle-structure).  This should allow using the `--target` flag to cross-compile a Rust app to iOS, and then bundle it into an iOS app that can e.g. be run on an iOS simulator for testing.

Implement iOS bundles

---

Readme.md

RE https://github.com/burtonageo/cargo-bundle/issues/21: Added a paragraph with instructions on installing cargo-bundle as a cargo subcommand.

Update Readme with installation instructions

---

src/bundle/common.rs
src/bundle/settings.rs

This change implements the suggestion in issue #5.  For now, the `Bundle.toml` file is still supported and will be used if found, but `cargo-bundle` will print a warning in that case, indicating that `[package.metadata.bundle]` should be used instead, and that support for `Bundle.toml` will eventually be removed.

Add support for [package.metadata.bundle] section in Cargo.toml

---

Cargo.lock
Cargo.toml
src/bundle/common.rs
src/bundle/deb_bundle.rs
src/bundle/ios_bundle.rs
src/bundle/mod.rs
src/bundle/osx_bundle.rs
src/bundle/settings.rs
src/main.rs

Use the `chain_err()` method from `error_chain` to give more context for lower-level errors, and tweak the formatting to better resemble errors from other cargo subcommands.

Improve error reporting

---

src/bundle/settings.rs
src/main.rs

Here is a WIP Pull-request that implements simple workspace awareness.
Care to take a look at give me some review comments / feedback?
I have left in some comments that go beyond the scope of the actual code changes as FYI.
I would take parts of them and make them separate enhancement issues for cargo-bundle if you agree, and remove the comments - so the comments match the code.
Note that I extracted CargoSettings from Settings (and used just Package) as:
- only the Package part of CargoSettings was actually used
- the CargoSettings implementation is now more alligned with all possible Cargo.toml files (where package is optional), so it can also be used for reading parent Cargo.toml files in a workspace

Workspace awareness

---

Readme.md
src/bundle/deb_bundle.rs
src/bundle/settings.rs

I expect more OS-specific settings to follow this one (see issue #33).  Hopefully most users won't need them (since, to me, part of the benefit of `cargo-bundle` is avoiding the need to worry about OS-specific details), but it's good to have these knobs when necessary.

Add OS-specific setting for Debian dependencies (fixes #25)

---

Cargo.lock
Cargo.toml
Readme.md
src/bundle/common.rs
src/bundle/osx_bundle.rs
src/bundle/settings.rs
src/main.rs

This provides an easy way to bundle frameworks that your binary depends on into your OS X app bundle.

Add OS-specific setting for OSX frameworks (for #33)

---

Cargo.lock
Cargo.toml
src/bundle/osx_bundle.rs
src/main.rs

`CFBundleShortVersionString` is the "human-readable" version number (e.g. "1.0.0"), whereas `CFBundleVersion` is supposed to be a monotonic build number that changes with every build (in particular, when submitting to the app store, each candidate build must have a different `CFBundleVersion` even if the human-readable version number stays the same).  To keep things simple, this PR just uses a UTC timestamp as the build number.

Use different values for CFBundleVersion and CFBundleShortVersionString

---

src/bundle/ios_bundle.rs

Removed "Resources" folder from iOS bundle
Described here https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1
Also, without CFBundleExecutable option in Info.plist bundle doesn't run on simulator. Added

An iOS app bundle cannot include a custom folder named “Resources.”

---

src/main.rs

Closes #81.
I don't actually know if this is the right way to do it. The `bail` macro returns an error type and it should presumably propigate the error up to a non-zero exit status code to main but that doesn't seem to be the case. Thoughts?

Use panic rather than bail to pass through the exit code

---

Readme.md
src/bundle/deb_bundle.rs
src/bundle/settings.rs

Enables programs bundled with cargo-bundle to be considered when selecting a program to "open with..." under GNOME.

Allow specifying the Exec field for the `.desktop`

---

Readme.md
src/bundle/deb_bundle.rs
src/bundle/settings.rs

Fixes #86. 
Please consider merging #87 first.

Allow specifying supported mime types for linux.

---

src/bundle/deb_bundle.rs

The version field in the desktop file does *not* specify the application version. Instead it refers to the version of the Desktop Entry Specification and if the provided version is not recognized by the system the desktop file may be refused to be installed as seen at https://github.com/ArturKovacs/emulsion/issues/162
It seems best to omit this field.

Omit the `Version` field from the desktop file

---

src/bundle/settings.rs
src/main.rs

This PR adds support for cargo's `--profile` option taking a single argument, being the name of the custom profile to use. This allows users to build bundles with custom cargo profiles. Cargo received the `--profile` feature in Rust 1.57.0. The cargo documentation specifies that the build directory used for a custom profile is `target/<profile-name>` where `<profile-name>` is the name of the profile being built. This PR accounts for the custom profile build directories and builds bundles in the proper sub-directories.
This PR closes #106.

Add support for --profile option

---

src/bundle/ios_bundle.rs

It looks like iOS [uses this field](https://stackoverflow.com/questions/56949674/uiwindow-not-filling-screen-for-new-devices) to determine if the app is a modern one that can support new device sizes; without it, the app content has a large black margin at the top and bottom of the app.
I feel like this is a reasonable flag to add to all apps, given how I can't imagine any production app would want to run in legacy cropped mode, but happy to try to convert this into a configuration parameter if that's not the case.
I tested this change by bundling an app and running on an iPhone 12 mini, and making sure this change fixed the cropping issue.
Fixes #91
Thanks for the great project! It's been working very well for me so far.

Add uilaunchstoryboardname key to ios plist files

---

src/bundle/osx_bundle.rs

On some versions of MacOS the default location of Apple frameworks is located at `/System/Library/Frameworks`. The documentation on Apple's [website](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html) makes reference to this location. So here, I've just added it to the search paths.

Add `/System/Library/Frameworks` to paths searched for Apple frameworks.

---

Readme.md
src/bundle/osx_bundle.rs
src/bundle/settings.rs

Through the `osx_url_schemes` property, users can specify URL schemes that will be placed in Info.plist and then picked up by the system on app launch.
Related to #33

Add support for URL schemes for macOS

---

Readme.md
src/bundle/deb_bundle.rs
src/bundle/settings.rs

Currently, cargo bundle hard code `Terminal=false`, which is not fitted with console applications.
This PR introduces a new parameter called `linux_use_terminal`,  a boolean variable indicating the app is a console app or a gui app, default it's set to false.

feat: support terminal app using cargo-bundle

---

src/bundle/settings.rs

Broken by a33aee1a52965e80b7482da8a837899ec94fa83c

Fix package lookup in Cargo metadata

---

Cargo.lock

`msi` package in Cargo.toml is v0.6 but the version in Cargo.lock is still 0.5. Just running `cargo build` in this repository causes file diffs due to the outdated lock file. This PR updates it to the latest.

Update outdated `Cargo.lock` lock file

---

Readme.md
src/bundle/settings.rs

Use `bin` target name instead of package name as default

---

Readme.md

Added the command flags and available targets to the ReadMe, as well as a note suggesting the use of MacOS runners/containers for creating installers for Mac without owning one.

readme (flags and targets)

---

src/bundle/settings.rs

note: this does not fix #161, since it doesn't read any `cargo.toml` config files.
The real fix is to use `cargo build --message-format json` and pick the correct artifact executable (like https://github.com/rust-lang/cargo/issues/6100#issuecomment-1435869969). I can do that in a follow-up PR but since it's probably a bit more controversial I wanted to open this simple fix first.

feat: respect CARGO_TARGET_DIR variable if set

---

src/bundle/settings.rs

This allows running `cargo bundle` on a project which has not been directly configured for it, which can be quite nice when using the iOS support to run under Mac Catalyst.
Example of such usage:
```
cargo +nightly build --target aarch64-apple-ios-macabi -Zbuild-std
CARGO_BUNDLE_SKIP_BUILD=1 cargo bundle --target aarch64-apple-ios-macabi --format ios
target/aarch64-apple-ios-macabi/debug/bundle/ios/my_app.app/my_app
```
This pairs especially well with https://github.com/burtonageo/cargo-bundle/pull/182.

Allow missing `package.metadata.bundle` section

---

src/bundle/settings.rs

These are by far not correct, but probably still better than having an empty bundle identifier.

Choose a default identifier for examples and binaries

---

Cargo.lock
Cargo.toml

I've compiled the user-facing changelog to be:
- macOS: Add support for URL schemes (#123)
- Linux: Support stating that the application is a terminal application (#124)
- iOS: Fix mismatch of the executable name in Info.plist and its real name (#127)
- Windows: Fix MSI support and add a minimal UI to the installer (#142)
- Find package which has `[package.metadata.bundle]` section in workspace (#155)
- Use `bin` target name instead of package name, if no other name was specified (#157)
- Linux: Fix `Installed-Size` (#160)
- The current working directory is now also considered a workspace root (#176)
- Allow building with a custom Cargo toolchain (#175)
- Respect `CARGO_TARGET_DIR` variable if set (#178)
- Allow missing `package.metadata.bundle` section (#183)
- Choose a default …

Release a new version (`v0.6.1`)

---

src/bundle/settings.rs

Hey,
I have `target-dir = './.build'` in my cargo config which the current code doesn't recognize.
Think this should be more consistent at finding the target dir - might fix #170 too?

use cargo to find target dir

---

Readme.md

Hello, thanks for making this convenient crate.
I tried to run it with `--bin` and was confused by how it didn't pick up the settings.
It turned out I have to put it in another section `[package.metadata.bundle.bin.<binary name>]`,
which was not very discoverable without reading the source code (or #51).
I've added it to the readme, what do you think?

Add documentation for settings of specified binaries

---

src/bundle/common.rs
src/bundle/osx_bundle.rs
src/bundle/settings.rs

Hello!
We're building a local app and need to add some additional keys into our `Info.plist` for requesting access to system services like the microphone. So I decided to take a crack at implementing https://github.com/burtonageo/cargo-bundle/issues/33 for MacOS. 
Current implementation is simple: 
- It adds a `osx_info_plist_exts` field into the bundle settings,
- It reads each file in that path, and blindly appends it's contents into the `Info.plist` file, after `cargo-bundle` has generated it's keys but before it closes the `<dict>` and `<plist>`.
I haven't written documentation for this yet, as I imagine folks here will have some thoughts on the name and behavior for this.
Let me know what you think!

Add option for copying keys into Info.plist on MacOS

---

src/main.rs

Cargo doesn't provide a short form for `--profile`.
Having this discrepancy in cargo-bundle was very confusing to me (since I very often type `cargo build -p my_crate`, but that did not work at all as `cargo bundle -p my_crate`).

Use short form `-p` for `--package`, not `--profile`
